// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	sql "database/sql"
	reflect "reflect"
	time "time"
	api "userbalance/pkg/api"

	gomock "github.com/golang/mock/gomock"
)

// MockControl is a mock of Control interface.
type MockControl struct {
	ctrl     *gomock.Controller
	recorder *MockControlMockRecorder
}

// MockControlMockRecorder is the mock recorder for MockControl.
type MockControlMockRecorder struct {
	mock *MockControl
}

// NewMockControl creates a new mock instance.
func NewMockControl(ctrl *gomock.Controller) *MockControl {
	mock := &MockControl{ctrl: ctrl}
	mock.recorder = &MockControlMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockControl) EXPECT() *MockControlMockRecorder {
	return m.recorder
}

// DeleteMoneyReserveDetailsTx mocks base method.
func (m *MockControl) DeleteMoneyReserveDetailsTx(tx *sql.Tx, userId, serviceId, orderId, amount int32, date time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMoneyReserveDetailsTx", tx, userId, serviceId, orderId, amount, date)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMoneyReserveDetailsTx indicates an expected call of DeleteMoneyReserveDetailsTx.
func (mr *MockControlMockRecorder) DeleteMoneyReserveDetailsTx(tx, userId, serviceId, orderId, amount, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMoneyReserveDetailsTx", reflect.TypeOf((*MockControl)(nil).DeleteMoneyReserveDetailsTx), tx, userId, serviceId, orderId, amount, date)
}

// GetBalanceReserveAccountsTx mocks base method.
func (m *MockControl) GetBalanceReserveAccountsTx(tx *sql.Tx, userId int32) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceReserveAccountsTx", tx, userId)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceReserveAccountsTx indicates an expected call of GetBalanceReserveAccountsTx.
func (mr *MockControlMockRecorder) GetBalanceReserveAccountsTx(tx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceReserveAccountsTx", reflect.TypeOf((*MockControl)(nil).GetBalanceReserveAccountsTx), tx, userId)
}

// GetHistory mocks base method.
func (m *MockControl) GetHistory(requestHistory *api.RequestHistory) ([]*api.History, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", requestHistory)
	ret0, _ := ret[0].([]*api.History)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockControlMockRecorder) GetHistory(requestHistory interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockControl)(nil).GetHistory), requestHistory)
}

// GetReport mocks base method.
func (m *MockControl) GetReport(fromDate, toDate time.Time) (map[string]int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReport", fromDate, toDate)
	ret0, _ := ret[0].(map[string]int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReport indicates an expected call of GetReport.
func (mr *MockControlMockRecorder) GetReport(fromDate, toDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReport", reflect.TypeOf((*MockControl)(nil).GetReport), fromDate, toDate)
}

// GetService mocks base method.
func (m *MockControl) GetService(serviceId int32) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetService", serviceId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetService indicates an expected call of GetService.
func (mr *MockControlMockRecorder) GetService(serviceId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetService", reflect.TypeOf((*MockControl)(nil).GetService), serviceId)
}

// GetUser mocks base method.
func (m *MockControl) GetUser(userId int32) (*api.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", userId)
	ret0, _ := ret[0].(*api.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockControlMockRecorder) GetUser(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockControl)(nil).GetUser), userId)
}

// GetUserForUpdate mocks base method.
func (m *MockControl) GetUserForUpdate(tx *sql.Tx, userId int32) (*api.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserForUpdate", tx, userId)
	ret0, _ := ret[0].(*api.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserForUpdate indicates an expected call of GetUserForUpdate.
func (mr *MockControlMockRecorder) GetUserForUpdate(tx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserForUpdate", reflect.TypeOf((*MockControl)(nil).GetUserForUpdate), tx, userId)
}

// InsertLogTx mocks base method.
func (m *MockControl) InsertLogTx(tx *sql.Tx, userId int32, date time.Time, amount int32, description string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertLogTx", tx, userId, date, amount, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertLogTx indicates an expected call of InsertLogTx.
func (mr *MockControlMockRecorder) InsertLogTx(tx, userId, date, amount, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertLogTx", reflect.TypeOf((*MockControl)(nil).InsertLogTx), tx, userId, date, amount, description)
}

// InsertMoneyReserveAccountsTx mocks base method.
func (m *MockControl) InsertMoneyReserveAccountsTx(tx *sql.Tx, userId int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMoneyReserveAccountsTx", tx, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertMoneyReserveAccountsTx indicates an expected call of InsertMoneyReserveAccountsTx.
func (mr *MockControlMockRecorder) InsertMoneyReserveAccountsTx(tx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMoneyReserveAccountsTx", reflect.TypeOf((*MockControl)(nil).InsertMoneyReserveAccountsTx), tx, userId)
}

// InsertMoneyReserveDetailsTx mocks base method.
func (m *MockControl) InsertMoneyReserveDetailsTx(tx *sql.Tx, userId, serviceId, orderId, amount int32, date time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMoneyReserveDetailsTx", tx, userId, serviceId, orderId, amount, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertMoneyReserveDetailsTx indicates an expected call of InsertMoneyReserveDetailsTx.
func (mr *MockControlMockRecorder) InsertMoneyReserveDetailsTx(tx, userId, serviceId, orderId, amount, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMoneyReserveDetailsTx", reflect.TypeOf((*MockControl)(nil).InsertMoneyReserveDetailsTx), tx, userId, serviceId, orderId, amount, date)
}

// InsertReportTx mocks base method.
func (m *MockControl) InsertReportTx(tx *sql.Tx, userId, serviceId, amount int32, date time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertReportTx", tx, userId, serviceId, amount, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertReportTx indicates an expected call of InsertReportTx.
func (mr *MockControlMockRecorder) InsertReportTx(tx, userId, serviceId, amount, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertReportTx", reflect.TypeOf((*MockControl)(nil).InsertReportTx), tx, userId, serviceId, amount, date)
}

// InsertUserTx mocks base method.
func (m *MockControl) InsertUserTx(tx *sql.Tx, userId, amount int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUserTx", tx, userId, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertUserTx indicates an expected call of InsertUserTx.
func (mr *MockControlMockRecorder) InsertUserTx(tx, userId, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUserTx", reflect.TypeOf((*MockControl)(nil).InsertUserTx), tx, userId, amount)
}

// UpdateBalanceTx mocks base method.
func (m *MockControl) UpdateBalanceTx(tx *sql.Tx, userId, amount int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalanceTx", tx, userId, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBalanceTx indicates an expected call of UpdateBalanceTx.
func (mr *MockControlMockRecorder) UpdateBalanceTx(tx, userId, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalanceTx", reflect.TypeOf((*MockControl)(nil).UpdateBalanceTx), tx, userId, amount)
}

// UpdateMoneyReserveAccountsTx mocks base method.
func (m *MockControl) UpdateMoneyReserveAccountsTx(tx *sql.Tx, userId, amount int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMoneyReserveAccountsTx", tx, userId, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMoneyReserveAccountsTx indicates an expected call of UpdateMoneyReserveAccountsTx.
func (mr *MockControlMockRecorder) UpdateMoneyReserveAccountsTx(tx, userId, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMoneyReserveAccountsTx", reflect.TypeOf((*MockControl)(nil).UpdateMoneyReserveAccountsTx), tx, userId, amount)
}
