version: '3.8'

services:
  db:
    container_name: db
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
       - dbdata:/var/lib/postgresql/data
  go:
    container_name: go
    ports:
      - "8081:8081"
    build:
      context: ../
    depends_on:
      - "db"
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata: