host : "db"
dbport : 5432
user : "postgres"
password : "postgres"
dbname : "postgres"
port : "8081"
connectiontype : "postgres"
contextimeout : 5
migrationpath : "./migrations"
readtimeout : 10
eritetimeout : 10