host : "localhost"
port : ":8081"
dbhost : "db"
dbport : 5432
user : "postgres"
password : "postgres"
dbname : "postgres"
connectiontype : "postgres"
contextimeout : 5
migrationpath : "./migrations"
readtimeout : 10
eritetimeout : 10