name: Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Verify dependencies
      run: go mod verify

    - name: Run handler tests
      run: go test ./internal/handler/ -v

    - name: Run service tests
      run: go test ./internal/service/ -v

    - name: Run repository tests
      run: go test ./internal/repository/ -v
